### ISSUE TITLE
Can't get debugging working in Visual Studio 2017

### ISSUE THREAD

**Issue by theobvious89** [greensponge/aurelia-dotnet-template#8]
Hi there,

So I've downloaded the template and everything works well except I'm unable to get debugging working in Visual Studio 2017. This is what I'm seeing.

![2019-03-02_21-47-23](https://user-images.githubusercontent.com/6792801/53682854-e15be300-3d34-11e9-86d7-a76a37eddeb9.jpg)

I think it may have something do to with Webpack, but I'm not sure. I've tried a bunch of different things in the Webpack config but I've had no luck. Does debugging work for you in Visual Studio?

I was on version 15.9.2 and it wasn't working, so I updated to the latest version of Visual Studio - 15.9.7, but that didn't change anything.

**Comment by greensponge** [comment]
Hello,

I didn't actually think it was possible in Visual Studio, but apparently if you are using Chrome or IE this seems to be working. If you select the arrow on the IIS Express button:

![script_debugging](https://user-images.githubusercontent.com/25538235/53683543-a6dd5080-3d0a-11e9-9fd9-a2d51311dd7d.JPG)

You can select "Enable script debugging", if you try to run with IE / Chrome it should also prompt you to enable this automatically when running the application with debugging, if you have a break point set.

Since it's working with at least these two, I think it should be possible with other browsers as well. Might need to do something clever with the source maps in those cases, however.

Please try doing this, it worked for me with a clean clone. I've confirmed it working in IE. Chrome didn't seem to work right away, but I don't normally use it, so it might be out of date.  

Let me know if you are still having issues. 

P.S. I was using VS2017 version 15.7.4 in the above tests, I don't see any reason it should be any different in more recent versions. If anything, it should be better.

**Comment by theobvious89** [comment]
Thanks for the reply. It does work fine in IE, just not Chrome. I have another project using an older aurelia-typescript-webpack skeleton and the Chrome debugging works fine in that. I've been comparing your one and this old one, trying various changes, but I've still not been able to get this project to debug in Chrome.

**Comment by greensponge** [comment]
I think I found a solution:

![image](https://user-images.githubusercontent.com/25538235/53693556-c035d980-3daa-11e9-8a51-70d5b611690f.png)

You need to go under Tools > Options > Debugging > General and tick the above box.

I found some obscure references somewhere where it worked for some people enabling both of these options. I updated my VS2017 to the latest version and confirmed that it works in Chrome (on my machine(tm)). 

Please give it a shot and let me know if it worked for you as well.
